[project]
name = 'Trustless-Peer-to-Peer-Rental-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.booking-system]
path = 'contracts/booking-system.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-nft]
path = 'contracts/rental-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
